name: threat_risk
version: "1.0.0"
config-version: 2

profile: threat_risk

model-paths: ["models"]

models:
  threat_risk:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

